# Generated by Django 5.2.8 on 2025-12-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_owner(apps, schema_editor):
    """Устанавливает владельца для существующих курсов и уроков"""
    Course = apps.get_model('lms', 'Course')
    Lesson = apps.get_model('lms', 'Lesson')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Получаем первого пользователя или создаем суперпользователя
    first_user = User.objects.first()
    if first_user:
        Course.objects.filter(owner__isnull=True).update(owner=first_user)
        Lesson.objects.filter(owner__isnull=True).update(owner=first_user)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Шаг 1: Добавляем поле как nullable
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL),
        ),
        # Шаг 2: Заполняем существующие записи
        migrations.RunPython(set_default_owner, migrations.RunPython.noop),
        # Шаг 3: Делаем поле обязательным
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
