# Generated by Django 5.2.8 on 2025-12-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-id']},
        ),
    ]
